// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RelationshipApi.Models.Entities;

namespace RelationshipApi.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20210619014249_dataSeeding")]
    partial class dataSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("RelationshipApi.Models.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DeliveryPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("RelationshipApi.Models.Entities.ProductOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductProductOptionFK")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductProductOptionFk")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductProductOptionFK");

                    b.ToTable("ProductOptions");
                });

            modelBuilder.Entity("RelationshipApi.Models.Entities.ProductOption", b =>
                {
                    b.HasOne("RelationshipApi.Models.Entities.Product", "Product")
                        .WithMany("ProductOptions")
                        .HasForeignKey("ProductProductOptionFK");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RelationshipApi.Models.Entities.Product", b =>
                {
                    b.Navigation("ProductOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
